# Generated by Django 5.2.5 on 2026-08-02 07:49

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0001_enable_pgvector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('dimension', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['dimension', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'dimension'), name='unique_tag_name_dimension')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('visibility', models.CharField(choices=[('department', 'Abteilung'), ('private', 'Privat')], default='department', max_length=20)),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('mail', 'E-Mail'), ('api', 'API')], default='upload', max_length=20)),
                ('processing_status', models.CharField(choices=[('pending', 'Ausstehend'), ('processing', 'In Verarbeitung'), ('done', 'Fertig'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20)),
                ('text_content', models.TextField(blank=True)),
                ('markdown', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('original_file', models.FileField(blank=True, upload_to='documents/%Y/%m/')),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('correspondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.correspondent')),
                ('departments', models.ManyToManyField(blank=True, related_name='documents', to='accounts.department')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_documents', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(blank=True, related_name='documents', to='documents.project')),
                ('tags', models.ManyToManyField(blank=True, related_name='documents', to='documents.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('embedding_model', models.CharField(max_length=100)),
                ('embedding_model_version', models.CharField(max_length=50)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'ordering': ['document_id', 'position'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw_idx', opclasses=['vector_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('document', 'position'), name='unique_chunk_position')],
            },
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_type', models.CharField(choices=[('related', 'Verwandt'), ('reply', 'Antwort auf'), ('attachment', 'Anhang von'), ('supersedes', 'Ersetzt')], default='related', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('from_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_from', to='documents.document')),
                ('to_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='documents.document')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_document', 'to_document', 'link_type'), name='unique_document_link')],
            },
        ),
    ]
