# Generated by Django 5.2.5 on 2026-08-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.CharField(choices=[('upload', 'Upload'), ('mail', 'E-Mail'), ('folder', 'Ordner-Überwachung'), ('api', 'API')], default='upload', max_length=20),
        ),
    ]
