# Generated by Django 5.2.5 on 2026-08-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('processing', 'In Verarbeitung'), ('ready', 'Bereit'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20),
        ),
    ]
