# Generated by Django 5.2.5 on 2026-08-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_processing_status_ready_and_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extraction_method',
            field=models.CharField(blank=True, choices=[('text_layer', 'Text-Layer'), ('ocr', 'OCR'), ('vision', 'Vision AI')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('extracting', 'Extraktion läuft'), ('embedding', 'Indizierung läuft'), ('ready', 'Bereit'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20),
        ),
    ]
