# Generated by Django 5.2.5 on 2026-08-02 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0005_document_extraction_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('pay', 'Zahlen'), ('review', 'Prüfen'), ('reply', 'Beantworten'), ('submit', 'Einreichen'), ('other', 'Sonstiges')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Offen'), ('done', 'Erledigt')], default='open', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('department', 'Abteilung'), ('private', 'Privat')], default='department', max_length=20)),
                ('departments', models.ManyToManyField(blank=True, related_name='tasks', to='accounts.department')),
                ('documents', models.ManyToManyField(blank=True, related_name='tasks', to='documents.document')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('is_done', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='documents.task')),
            ],
            options={
                'ordering': ['task_id', 'order'],
            },
        ),
    ]
