# Generated by Django 5.2.5 on 2026-08-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_task_checklistitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Vorgang',
        ),
        migrations.AlterModelOptions(
            name='vorgang',
            options={'ordering': ['name'], 'verbose_name': 'Vorgang', 'verbose_name_plural': 'Vorgänge'},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='projects',
            new_name='vorgaenge',
        ),
    ]
