# Generated by Django 5.2.15 on 2026-08-02 21:04

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_rename_project_to_vorgang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
    ]
