# Generated by Django 5.2.15 on 2026-08-02 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_rename_project_to_vorgang'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='key_facts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('extracting', 'Extraktion läuft'), ('analyzing', 'Analyse läuft'), ('embedding', 'Indizierung läuft'), ('ready', 'Bereit'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TagSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('dimension', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('accepted', 'Angenommen'), ('rejected', 'Verworfen')], default='pending', max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_suggestions', to='documents.document')),
            ],
            options={
                'ordering': ['-confidence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VorgangSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('accepted', 'Angenommen'), ('rejected', 'Verworfen')], default='pending', max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vorgang_suggestions', to='documents.document')),
            ],
            options={
                'ordering': ['-confidence', 'name'],
            },
        ),
    ]
