# Generated by Django 5.2.5 on 2026-08-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_chunk_embedding'),
        ('documents', '0008_ki_analyse_summary_key_facts_suggestions'),
    ]

    operations = [
    ]
