# Generated by Django 5.2.5 on 2026-08-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_merge_20260803_0834'),
        ('documents', '0009_merge_20260803_0844'),
    ]

    operations = [
    ]
