# Generated by Django 5.2.5 on 2026-08-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_merge_20260803_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondent',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='correspondent',
            name='is_self',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='correspondent',
            name='tax_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='correspondent',
            name='vat_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='document',
            name='direction',
            field=models.CharField(choices=[('eingang', 'Eingang'), ('ausgang', 'Ausgang'), ('intern', 'Intern'), ('unbekannt', 'Unbekannt')], db_index=True, default='unbekannt', max_length=20),
        ),
    ]
