# Generated by Django 5.2.15 on 2026-08-03 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0013_repair_stuck_analyzing_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('default_kind', models.CharField(blank=True, choices=[('pay', 'Zahlen'), ('review', 'Prüfen'), ('reply', 'Beantworten'), ('submit', 'Einreichen'), ('other', 'Sonstiges')], max_length=20)),
                ('default_title', models.CharField(blank=True, max_length=255)),
                ('default_description', models.TextField(blank=True)),
                ('default_due_offset_days', models.PositiveIntegerField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('department', 'Abteilung'), ('private', 'Privat')], default='department', max_length=20)),
                ('departments', models.ManyToManyField(blank=True, related_name='task_templates', to='accounts.department')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_task_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.tasktemplate')),
            ],
            options={
                'ordering': ['template_id', 'order'],
            },
        ),
    ]
