# Generated by Django 5.2.15 on 2026-08-03 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0014_tasktemplate_tasktemplateitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondent',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vorgang',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vorgaenge', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='vorgang',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vorgang',
            name='status',
            field=models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('closed', 'Abgeschlossen')], default='open', max_length=20),
        ),
    ]
