# Generated by Django 5.2.15 on 2026-08-03 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_correspondent_address_vorgang_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Farbe muss ein Hex-Code sein, z. B. #a1b2c3.', regex='^#[0-9a-fA-F]{6}$')]),
        ),
    ]
