# Generated by Django 5.2.15 on 2026-08-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_drop_orphaned_correspondent_address'),
        ('documents', '0016_tag_color'),
    ]

    operations = [
    ]
