# Generated by Django 5.2.15 on 2026-08-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='action_status',
            field=models.CharField(choices=[('keine', 'Kein Handlungsbedarf'), ('offen', 'Offen'), ('erledigt', 'Erledigt')], db_index=True, default='keine', max_length=20),
        ),
    ]
