# Generated by Django 5.2.15 on 2026-08-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_merge_20260803_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondent',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
