# Generated by Django 5.2.15 on 2026-08-03 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_document_action_status'),
        ('documents', '0018_alter_correspondent_address_default'),
    ]

    operations = [
    ]
