# Generated by Django 5.2.15 on 2026-08-03 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_merge_20260803_1750'),
        ('documents', '0019_merge_20260803_2130'),
    ]

    operations = [
    ]
