# Generated by Django 5.2.15 on 2026-08-05 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_merge_20260803_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='child_role',
            field=models.CharField(blank=True, choices=[('mail_attachment', 'Mail-Anhang'), ('embedded', 'Eingebettet'), ('nachtrag', 'Nachtrag'), ('version', 'Version')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.document'),
        ),
        migrations.DeleteModel(
            name='DocumentLink',
        ),
    ]
