# Generated by Django 5.2.15 on 2026-08-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_document_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
