# Generated by Django 5.2.15 on 2026-08-09 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_documentlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='VorgangRecommendationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Wird erstellt'), ('ready', 'Fertig'), ('failed', 'Fehlgeschlagen')], default='running', max_length=20)),
                ('situation', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('based_on', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('ai_model_version', models.CharField(blank=True, max_length=50)),
                ('vorgang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_run', to='documents.vorgang')),
            ],
            options={
                'verbose_name': 'Handlungsempfehlungen',
                'verbose_name_plural': 'Handlungsempfehlungen',
            },
        ),
        migrations.CreateModel(
            name='VorgangRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('rationale', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('hoch', 'Hoch'), ('mittel', 'Mittel'), ('niedrig', 'Niedrig')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Offen'), ('accepted', 'Übernommen'), ('dismissed', 'Verworfen')], default='open', max_length=20)),
                ('documents', models.ManyToManyField(blank=True, related_name='vorgang_recommendations', to='documents.document')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_recommendations', to='documents.task')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='documents.vorgangrecommendationrun')),
            ],
            options={
                'verbose_name': 'Handlungsempfehlung',
                'verbose_name_plural': 'Handlungsempfehlungen',
                'ordering': ['run_id', 'order', 'pk'],
            },
        ),
    ]
