# Generated by Django 5.2.15 on 2026-08-09 14:34

import apps.documents.letter_bindings
import apps.documents.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0025_vorgangrecommendationrun_vorgangrecommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('layout', models.JSONField(blank=True, default=apps.documents.models.default_letter_layout)),
                ('signature', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='letter_templates/logos/')),
                ('visibility', models.CharField(choices=[('department', 'Abteilung'), ('private', 'Privat')], default='department', max_length=20)),
                ('departments', models.ManyToManyField(blank=True, related_name='letter_templates', to='accounts.department')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_letter_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brief-Vorlage',
                'verbose_name_plural': 'Brief-Vorlagen',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LetterTemplatePlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Schlüssel: nur Kleinbuchstaben, Ziffern und Unterstrich, beginnend mit einem Buchstaben (z. B. empfaenger_adresse).', regex='^[a-z][a-z0-9_]*$')])),
                ('label', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(max_length=100, validators=[apps.documents.letter_bindings.validate_source])),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholders', to='documents.lettertemplate')),
            ],
            options={
                'verbose_name': 'Platzhalter',
                'verbose_name_plural': 'Platzhalter',
                'ordering': ['template_id', 'order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('template', 'key'), name='unique_letter_placeholder_key')],
            },
        ),
    ]
