# Generated by Django 5.2.15 on 2026-08-09 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0026_lettertemplate_lettertemplateplaceholder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.CharField(choices=[('upload', 'Upload'), ('mail', 'E-Mail'), ('folder', 'Ordner-Überwachung'), ('api', 'API'), ('generiert_brief', 'Generiert (Brief)')], default='upload', max_length=20),
        ),
        migrations.CreateModel(
            name='LetterDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('running', 'Wird erstellt'), ('ready', 'Entwurf bereit'), ('failed', 'Fehlgeschlagen'), ('finalized', 'Abgelegt')], default='running', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('letter_date', models.DateField(blank=True, null=True)),
                ('sender_block', models.TextField(blank=True)),
                ('recipient_block', models.TextField(blank=True)),
                ('signature', models.TextField(blank=True)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('manual_values', models.JSONField(blank=True, default=dict)),
                ('placeholder_values', models.JSONField(blank=True, default=dict)),
                ('docx_file', models.FileField(blank=True, upload_to='letters/%Y/%m/')),
                ('pdf_file', models.FileField(blank=True, upload_to='letters/%Y/%m/')),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('ai_model_version', models.CharField(blank=True, max_length=50)),
                ('visibility', models.CharField(choices=[('department', 'Abteilung'), ('private', 'Privat')], default='department', max_length=20)),
                ('departments', models.ManyToManyField(blank=True, related_name='letter_drafts', to='accounts.department')),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_draft', to='documents.document')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_letter_drafts', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_drafts_received', to='documents.correspondent')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_drafts_sent', to='documents.correspondent')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_drafts', to='documents.document')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='documents.lettertemplate')),
                ('vorgang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_drafts', to='documents.vorgang')),
            ],
            options={
                'verbose_name': 'Brief-Entwurf',
                'verbose_name_plural': 'Brief-Entwürfe',
                'ordering': ['-created_at'],
            },
        ),
    ]
