# Generated by Django 5.2.15 on 2026-08-09 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_alter_document_source_letterdraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('aktenzeichen', 'Aktenzeichen'), ('forderungsnummer', 'Forderungsnummer'), ('kundennummer', 'Kundennummer'), ('belegnummer', 'Belegnummer'), ('rechnungsnummer', 'Rechnungsnummer'), ('vertragsnummer', 'Vertragsnummer'), ('iban', 'IBAN'), ('ihr_zeichen', 'Ihr Zeichen'), ('unser_zeichen', 'Unser Zeichen'), ('sonstige', 'Sonstige')], max_length=30)),
                ('value_raw', models.CharField(max_length=255)),
                ('value_normalized', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, choices=[('deins', 'Unsere Kennung'), ('deren', 'Kennung der Gegenstelle')], default='', max_length=10)),
                ('source', models.CharField(choices=[('ki', 'KI-Analyse'), ('manuell', 'Manuell')], default='ki', max_length=10)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='documents.document')),
            ],
            options={
                'verbose_name': 'Kennung',
                'verbose_name_plural': 'Kennungen',
                'ordering': ['type', 'value_normalized', 'pk'],
                'indexes': [models.Index(fields=['type', 'value_normalized'], name='document_reference_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'type', 'value_normalized'), name='unique_document_reference')],
            },
        ),
    ]
