# Generated by Django 5.2.15 on 2026-08-09 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_documentreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrespondentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('aktenzeichen', 'Aktenzeichen'), ('forderungsnummer', 'Forderungsnummer'), ('kundennummer', 'Kundennummer'), ('belegnummer', 'Belegnummer'), ('rechnungsnummer', 'Rechnungsnummer'), ('vertragsnummer', 'Vertragsnummer'), ('iban', 'IBAN'), ('ihr_zeichen', 'Ihr Zeichen'), ('unser_zeichen', 'Unser Zeichen'), ('sonstige', 'Sonstige')], max_length=30)),
                ('value_raw', models.CharField(max_length=255)),
                ('value_normalized', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('manuell', 'Manuell'), ('gelernt', 'Aus Dokument gelernt')], default='manuell', max_length=10)),
                ('correspondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='documents.correspondent')),
                ('learned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
            ],
            options={
                'verbose_name': 'Kontakt-Kennung',
                'verbose_name_plural': 'Kontakt-Kennungen',
                'ordering': ['type', 'value_normalized', 'pk'],
                'abstract': False,
                'indexes': [models.Index(fields=['type', 'value_normalized'], name='correspondent_ref_idx')],
                'constraints': [models.UniqueConstraint(fields=('correspondent', 'type', 'value_normalized'), name='unique_correspondent_reference')],
            },
        ),
        migrations.CreateModel(
            name='VorgangReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('aktenzeichen', 'Aktenzeichen'), ('forderungsnummer', 'Forderungsnummer'), ('kundennummer', 'Kundennummer'), ('belegnummer', 'Belegnummer'), ('rechnungsnummer', 'Rechnungsnummer'), ('vertragsnummer', 'Vertragsnummer'), ('iban', 'IBAN'), ('ihr_zeichen', 'Ihr Zeichen'), ('unser_zeichen', 'Unser Zeichen'), ('sonstige', 'Sonstige')], max_length=30)),
                ('value_raw', models.CharField(max_length=255)),
                ('value_normalized', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('manuell', 'Manuell'), ('gelernt', 'Aus Dokument gelernt')], default='manuell', max_length=10)),
                ('learned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
                ('vorgang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='documents.vorgang')),
            ],
            options={
                'verbose_name': 'Vorgang-Kennung',
                'verbose_name_plural': 'Vorgang-Kennungen',
                'ordering': ['type', 'value_normalized', 'pk'],
                'abstract': False,
                'indexes': [models.Index(fields=['type', 'value_normalized'], name='vorgang_reference_idx')],
                'constraints': [models.UniqueConstraint(fields=('vorgang', 'type', 'value_normalized'), name='unique_vorgang_reference')],
            },
        ),
    ]
