# Generated by Django 5.2.15 on 2026-08-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_correspondentreference_vorgangreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondent',
            name='is_own_business',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='sphere',
            field=models.CharField(choices=[('geschaeftlich', 'Geschäftlich'), ('privat', 'Privat'), ('unbekannt', 'Unbekannt')], db_index=True, default='unbekannt', max_length=20),
        ),
    ]
