# Generated by Django 5.2.15 on 2026-08-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_document_tax_relevance'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='thumbnails/%Y/%m/'),
        ),
    ]
