# Generated by Django 5.2.15 on 2026-08-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0033_documentcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='long_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='long_summary_ai_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='long_summary_ai_model_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='long_summary_based_on',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='document',
            name='long_summary_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='long_summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='long_summary_run_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='long_summary_status',
            field=models.CharField(choices=[('none', 'Nicht erstellt'), ('running', 'Wird erstellt'), ('ready', 'Fertig'), ('failed', 'Fehlgeschlagen')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='vorgang',
            name='long_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vorgang',
            name='long_summary_ai_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vorgang',
            name='long_summary_ai_model_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vorgang',
            name='long_summary_based_on',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vorgang',
            name='long_summary_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vorgang',
            name='long_summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vorgang',
            name='long_summary_run_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vorgang',
            name='long_summary_status',
            field=models.CharField(choices=[('none', 'Nicht erstellt'), ('running', 'Wird erstellt'), ('ready', 'Fertig'), ('failed', 'Fehlgeschlagen')], default='none', max_length=20),
        ),
    ]
