# Generated by Django 5.2.15 on 2026-08-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0035_document_date_source_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='vision_reextraction_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='vision_reextraction_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='vision_reextraction_pages_processed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='vision_reextraction_pages_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='vision_reextraction_run_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='vision_reextraction_status',
            field=models.CharField(choices=[('none', 'Nicht ausgeführt'), ('running', 'Läuft'), ('ready', 'Fertig'), ('failed', 'Fehlgeschlagen')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='vision_reextraction_truncated',
            field=models.BooleanField(default=False),
        ),
    ]
