# Generated by Django 5.2.15 on 2026-08-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0036_document_vision_reextraction_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='vision_reextraction_fingerprint',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
