# Generated by Django 5.2.15 on 2026-08-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0036_document_vision_reextraction_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_format',
            field=models.CharField(choices=[('text', 'Text'), ('markdown', 'Markdown')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='vision_reextraction_fingerprint',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='document',
            name='vision_reextraction_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='vision_reextraction_model_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='vision_reextraction_number_check',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='document',
            name='vision_reextraction_pages_failed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
