# Generated by Django 5.2.15 on 2026-08-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0037_document_content_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondent',
            name='phone',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
