# Generated by Django 5.2.15 on 2026-08-17 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0038_correspondent_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processing_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('extracting', 'Extraktion läuft'), ('analyzing', 'Analyse läuft'), ('embedding', 'Indizierung läuft'), ('ready', 'Zu prüfen'), ('reviewed', 'Geprüft'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20),
        ),
    ]
