# Generated by Django 5.2.15 on 2026-08-19 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0040_document_reviewed_backfill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPdfEditRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_title', models.CharField(blank=True, max_length=255)),
                ('mode', models.CharField(choices=[('edit', 'Seiten bearbeitet'), ('split', 'Aufgeteilt')], default='edit', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Wird ausgeführt'), ('ready', 'Fertig'), ('failed', 'Fehlgeschlagen')], default='running', max_length=20)),
                ('plan', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_edit_runs', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_edit_runs', to='documents.document')),
            ],
            options={
                'verbose_name': 'PDF-Seitenbearbeitung',
                'verbose_name_plural': 'PDF-Seitenbearbeitungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPagePreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField()),
                ('image', models.FileField(upload_to='page-previews/%Y/%m/')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_previews', to='documents.document')),
            ],
            options={
                'ordering': ['document_id', 'page_number'],
                'constraints': [models.UniqueConstraint(fields=('document', 'page_number'), name='unique_document_page_preview')],
            },
        ),
    ]
